### ISSUE TITLE
Apple publisher addresses two feeds

### ISSUE THREAD

**Issue by svevang** [PRX/feeder.prx.org#470]
Refactor the apple publisher model to take in:

- [x] A primary/subscribe-able public feed
- [x] A private feed that is the source of the premium content.
- [x] Apple API credentials

- [x] Pull from the private feed + CDN (w/ a token if needed)

**Comment by cavis** [comment]
Since the `AppleCredential` contains the foreign keys to both `Feed`s ... could we just allow null key/pem on it, which indicates to use the default/ENV credentials?

Then you could _just_ take in a `AppleCredential` and get all the info you need.  (And figuring out which to sync would be as easy as `AppleCredential.all.each`).
